name: Run the job

on:
  schedule:
  - cron:  '15 1 * * *'
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Checkout and patch VPP
        run: |
          scripts/checkout-vpp

      - name: Build VPP
        run: |
          scripts/build-vpp

      - name: Test VPP
        run: |
          scripts/test-vpp
